CLOUDINARY_URL: cloudinary://492515569163668:jEA99Z9HzGrCwydKRN7JvifWfBM@julie


development:
  CLOUDINARY_CLOUD_NAME: 'julie'
  CLOUDINARY_API_KEY: '492515569163668'
  CLOUDINARY_API_SECRET: 'jEA99Z9HzGrCwydKRN7JvifWfBM'

production:
  CLOUDINARY_CLOUD_NAME: 'julie'
  CLOUDINARY_API_KEY: '492515569163668'
  CLOUDINARY_API_SECRET: 'jEA99Z9HzGrCwydKRN7JvifWfBM'
  SENDGRID_USERNAME: 'JulieBrosse'
  SENDGRID_PASSWORD: 'BRDONJU25america.'
  HEROKU_DOMAIN: 'https://coolingtech.herokuapp.com/'
